version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.3
  shellcheck: circleci/shellcheck@3.2

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          orb_name: mvn-ci
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: mvn-ci
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
      - orb-tools/publish:
          orb_name: snowbird/mvn-ci
          vcs_type: github
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/continue
          context: <publishing-context>
          filters: *release-filters
